import { jsPDF } from 'jspdf';
import type { ScanResult, WalletState } from '../types/sentinel';

const PRIMARY = [255, 59, 48] as const; // matches the app's --primary red
const MUTED = [120, 120, 120] as const;

function certificateId(scan: ScanResult): string {
  const hash = scan.targetAddress.slice(2, 8).toUpperCase();
  return `SEN-OKX-${hash}`;
}

/**
 * Builds a real PDF audit certificate from a completed scan and triggers a
 * browser download. Pure client-side - no backend round trip needed.
 */
export function downloadAuditPdf(scan: ScanResult, wallet: WalletState): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = 64;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...PRIMARY);
  doc.text('SENTINEL AI - CERTIFICATE OF AUDIT', margin, y);

  y += 20;
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.setFont('helvetica', 'normal');
  doc.text('Smart Contract Security Pass - OKX X Layer', margin, y);

  y += 12;
  doc.setDrawColor(...PRIMARY);
  doc.line(margin, y, pageWidth - margin, y);
  y += 28;

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  const issued = new Date().toISOString().slice(0, 10);
  const rows: [string, string][] = [
    ['Certificate ID', certificateId(scan)],
    ['Issued', issued],
    ['Audited Target', scan.targetName],
    ['Target Address', scan.targetAddress],
    ['Network', scan.network],
    ['Wallet', wallet.isConnected ? wallet.address : 'Not connected'],
    ['Risk Score', `${scan.riskScore} / 100`],
    ['Risk Level', scan.riskLevel],
  ];
  for (const [label, value] of rows) {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), margin + 140, y);
    y += 18;
  }

  y += 12;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Automated AI Vector Matrix', margin, y);
  y += 18;

  doc.setFontSize(10);
  for (const check of scan.checks) {
    const statusLabel = check.status.toUpperCase();
    doc.setFont('helvetica', 'bold');
    doc.text(`[${statusLabel}] ${check.label}`, margin, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    const wrapped = doc.splitTextToSize(check.details, pageWidth - margin * 2 - 12);
    doc.text(wrapped, margin + 12, y);
    y += wrapped.length * 12 + 8;
    doc.setTextColor(30, 30, 30);
  }

  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('AI Plain-English Explanation', margin, y);
  y += 18;

  const sections: [string, string][] = [
    ['What We Found', scan.aiExplanation.whatWeFound],
    ['Why It Matters', scan.aiExplanation.whyItMatters],
    ['Potential Impact', scan.aiExplanation.potentialImpact],
    ['Recommended Action', scan.aiExplanation.recommendedAction],
  ];
  doc.setFontSize(10);
  for (const [label, text] of sections) {
    if (y > 740) {
      doc.addPage();
      y = 64;
    }
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, margin, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    const wrapped = doc.splitTextToSize(text, pageWidth - margin * 2);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 12 + 12;
  }

  y += 8;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 16;
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(
    'Generated by Sentinel - automated on-chain analysis. Not a substitute for professional security review.',
    margin,
    y
  );

  doc.save(`${certificateId(scan)}-sentinel-audit.pdf`);
}
